#!/usr/bin/env python

import argparse

from pygments.lexers import HtmlLexer

# =============================================================================

parser = argparse.ArgumentParser(description=('Prints out the tokens ' 
    'generated by pygments.lexers.HtmlLexer'))
parser.add_argument('files', type=str, nargs='+',
    help='One or more file names to lex and parse')

args = parser.parse_args()

# --- Do the parsing

lexer = HtmlLexer()
with open(args.files[0]) as f:
    contents = f.read()

for token, text in lexer.get_tokens(contents):
    first = ord(text[0])
    if text == '\n':
        text = '\\n'

    print('%s: %s %0x' % (token, text, first))
