#!/usr/bin/env python

import argparse

from pygments.lexers import PythonConsoleLexer, PythonLexer

# =============================================================================

parser = argparse.ArgumentParser(description=('Prints out the tokens ' 
    'generated by pygments.lexers.PythonConsoleLexer'))
parser.add_argument('-p', '--py3', action='store_true', 
    help='Change lexer to Python 3 instead of console')
parser.add_argument('files', type=str, nargs='+',
    help='One or more file names to lex and parse')

args = parser.parse_args()

# --- Do the parsing

lexer = PythonConsoleLexer()
if args.py3:
    lexer = PythonLexer()

with open(args.files[0]) as f:
    contents = f.read()

for token, text in lexer.get_tokens(contents):
    if text == '\n':
        text = '\\n'

    print('%s: %s' % (token, text))
